version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:7.3.1
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #transaction.state.log.replication.factor
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      #transaction.state.log.min.isr
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  api:
    image: kafka-demo/counter-api:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose

  consumer:
    image: kafka-demo/msg-consumer:latest
    depends_on:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
      SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS: "broker:9092"

  deadletter:
    image: kafka-demo/deadletter-consumer:latest
    container_name: deadletter
    depends_on:
      - broker
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
      SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS: "broker:9092"

  producer:
    image: kafka-demo/gen-msg-producer:latest
    depends_on:
      - broker
      - consumer
    environment:
      SPRING_PROFILES_ACTIVE: docker-compose
      SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS: "broker:9092"
      MESSAGE_INTERVAL: 1000


