apiVersion: apps/v1
kind: Deployment
metadata:
  name: deadletter-consumer-deployment
spec:
  selector:
    matchLabels:
      app: deadletter-consumer
  template:
    metadata:
      labels:
        app: deadletter-consumer
    spec:
      containers:
      - name: deadletter-consumer
        image: localhost:32000/kafka-demo/msg-consumer
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: microk8s
          - name: SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS
            value: broker-service:9092