apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: localhost:32000/kafka-demo/msg-producer
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: microk8s
          - name: SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS
            value: broker-service:9092
          - name: MESSAGE_INTERVAL
            value: "9000"
