apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-consumer-deployment
spec:
  selector:
    matchLabels:
      app: msg-consumer
  replicas: 3
  template:
    metadata:
      labels:
        app: msg-consumer
    spec:
      containers:
      - name: msg-consumer
        image: localhost:32000/kafka-demo/msg-consumer
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: microk8s
          - name: SPRING_KAFKA_PROPERTIES_BOOTSTRAP_SERVERS
            value: broker-service:9092
          - name: API_HOST
            value: counter-api-service
          - name: API_PORT
            value: "8080"
